CREATE TABLE dbo.SKU (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	Code AS 's' + CAST(ID AS VARCHAR(10)),
	NAME NVARCHAR(50),
	CONSTRAINT UQ_Code UNIQUE (Code)
	);

CREATE TABLE dbo.Family (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	SurName varchar(255),
	BudgetValue DECIMAL(18, 2)
	);

CREATE TABLE dbo.Basket (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	ID_SKU INT,
	ID_Family INT,
	Quantity INT CHECK (Quantity >= 0),
	Value DECIMAL(18, 2) CHECK (Value >= 0),
	PurchaseDate DATETIME DEFAULT GETDATE(),
	DiscountValue DECIMAL(10, 2),
	CONSTRAINT FK_IDSku FOREIGN KEY (ID_SKU) REFERENCES dbo.SKU(ID),
	CONSTRAINT FK_IDFamily FOREIGN KEY (ID_Family) REFERENCES dbo.Family(ID)
	);